<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>Edmondo Silvestri</Authors>
    <Company>Edmondo Silvestri</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/3Dmondo/SpiceNet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>SPICE;Ephemeris;Astronomy;NAIF</PackageTags>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSource>true</IncludeSource>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>
</Project>
