name: Monthly SSD Ephemerides Catalog Update

on:
  schedule:
    - cron: '0 3 1 * *'   # 03:00 UTC on the 1st of every month
  workflow_dispatch:      # allow manual trigger

permissions:
  contents: write        # needed to push branch
  pull-requests: write   # needed to open PR

concurrency:
  group: monthly-ssd-catalog
  cancel-in-progress: false

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Run SSD Catalog tool (stable mode)
        id: run_tool
        run: |
          set -e
          OUTPUT=$(dotnet run --configuration Release --project Spice.SsdCatalog/Spice.SsdCatalog.csproj -- --stable --include-testpo | tee /dev/stderr)
          echo "raw-output<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          if echo "$OUTPUT" | grep -q 'SSDCATALOG:CHANGED'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            HASH=$(echo "$OUTPUT" | sed -n 's/.*SSDCATALOG:CHANGED //p' | head -n1)
            echo "hash=$HASH" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            HASH=$(echo "$OUTPUT" | sed -n 's/.*SSDCATALOG:NO_CHANGE //p' | head -n1)
            echo "hash=$HASH" >> $GITHUB_OUTPUT
          fi

      - name: Stage updated artifacts
        if: steps.run_tool.outputs.changed == 'true'
        run: |
          git add Docs/SsdCatalog/ssd_catalog.json Docs/SsdCatalog/testpo_catalog.json Docs/SsdCatalog/SSDCatalog.md Docs/SsdCatalog/catalog.hash || true

      - name: Create Pull Request
        if: steps.run_tool.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: monthly SSD ephemerides catalog refresh (${{ steps.run_tool.outputs.hash }})"
          branch: chore/update-ssd-catalog-${{ github.run_id }}
          title: "Monthly SSD Ephemerides Catalog Refresh"
          body: |
            Automated monthly refresh of JPL SSD BSP catalog.

            Run output hash: `${{ steps.run_tool.outputs.hash }}`

            Generated by workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

            Updated artifacts (written only if content changed):
            - Docs/SsdCatalog/ssd_catalog.json
            - Docs/SsdCatalog/testpo_catalog.json (when testpo flag enabled)
            - Docs/SsdCatalog/SSDCatalog.md
            - Docs/SsdCatalog/catalog.hash (content signature)

            Please review and merge.
          labels: |
            automated
            documentation
          add-paths: |
            Docs/SsdCatalog/**

      - name: No changes
        if: steps.run_tool.outputs.changed != 'true'
        run: echo "No catalog content changes detected (hash=${{ steps.run_tool.outputs.hash }}); skipping PR."